name: Run Python Program

on:
  push:
    paths:
      - '**.json'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # replace with the version of Python you're using
    - name: Run Python program
      run: python sample1.py # replace with the name of your Python program
      env:
        FILE_PATH: ${{ github.event.head_commit.modified[0] }} # pass the path of the modified file as an environment variable
