name: Run Python Program

on:
  push:
    paths:
      - '**.json'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Clone z3 repository
      uses: actions/checkout@v2
      with:
        repository: Z3Prover/z3
        ref: master
    - name: List files in directory
      run: ls
      working-directory: z3 # set the working directory to the cloned repository directory
    - name: Install z3 solver
      run: |
        cd z3
        python scripts/mk_make.py
        cd build
        make
      shell: bash
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # replace with the version of Python you're using
    - name: Install dependencies
      run: pip install -r requirements.txt # replace with the name of your requirements file, if any
    - name: Run Python program
      run: python sample1.py # replace with the name of your Python program
      env:
        FILE_PATH: ${{ github.event.head_commit.modified[0] }} # pass the path of the modified file as an environment variable
